---
# key-value mapping of actor-leak site URL
sites:
  conti: http://continewsnv5otx5kaoje7krkto2qbu3gtqef22mnr7eaxw3y6ncz3ad.onion.ly/
  revil: http://dnpscnbaix6nkwvystl3yxglz7nteicqrou3t75tpcc5532cztc46qyd.onion.ly/
  ##avaddon: http://something.onion
  ##darkside: http://something.onion
  babuk: http://nq4zyac4ukl4tykmidbzgdlvaboqeqsemkp4t35bzvjeve6zm2lqcjid.onion.ly/
  ##ranzy: http://something.onion
  ##astro: http://something.onion
  pay2key: http://pay2key2zkg7arp3kv3cuugdaqwuesifnbofun4j6yjdw5ry7zw2asid.onion.ws/
  cuba: http://cuba4ikm4jakjgmkezytyawtdgr2xymvy6nvzgw5cglswg3si76icnqd.onion.ly/
  ##ransomexx: http://something.onion
  mount: http://rnsm777cdsjrsdlbs4v5qoeppu3px6sb2igmh53jzrx7ipcrbjz5b2ad.onion.ws/
  ragnarok: http://sushlnty2j7qdzy64qnvyb6ajkwg7resd3p6agc2widnawodtcedgjid.onion.ly/
  ragnar: http://rgleaktxuey67yrgspmhvtnrqtgogur35lwdrup4d3igtbm3pupc4lyd.onion.ws/
  suncrypt: http://x2miyuiwpib2imjr5ykyjngdu7v6vprkkhjltrk4qafymtawey4qzwid.onion.ly/
  everest: https://ransomocmou6mnbquqz44ewosbkjk3o5qjsl3orawojexfook2j7esad.onion.ws/
  ##nefilim: http://something.onion
  cl0p: http://santat7kpllt6iyvqbr7q4amdv6dzrh6paatvyrzl7ry3zm72zigf4ad.onion.ly/
  pysa: http://pysa2bitc5ldeyfak4seeruqymqs4sj5wt5qkcq7aoyg4h2acqieywad.onion.ws/
  lockbit: http://lockbitapt6vx57t3eeqjofwgcglmutr3a35nygvokja5uuccip4ykyd.onion.ly/
  xing: http://xingnewj6m4qytljhfwemngm7r7rogrindbq7wrfeepejgxc3bwci7qd.onion.ws/
  lorenz: http://lorenzmlwpzgxq736jzseuterytjueszsvznuibanxomlpkyxk6ksoyd.onion.ly/
  ##elcometa: http://something.onion
  arvin: http://3kp6j22pz3zkv76yutctosa6djpj4yib2icvdqxucdaxxedumhqicpad.onion.ly/
  blackmatter: http://blackmax7su6mbwtcyo3xwtpfxpm356jjqrs34y4crcytpw7mifuedyd.onion.ly/
  avoslocker: http://avosqxh72b5ia23dl5fgwcpndkctuzqvh2iefk5imp3pi5gfhel5klad.onion.ly/
  lv: http://rbvuetuneohce3ouxjlbxtimyyxokb4btncxjbo44fbgxqy7tskinwad.onion.ly/
  marketo: http://jvdamsif53dqjycuozlaye2s47p7xij4x6hzwzwhzrqmv36gkyzohhqd.onion.ly/
  lockdata: http://wm6mbuzipviusuc42kcggzkdpbhuv45sn7olyamy6mcqqked3waslbqd.onion.ly/
  # this has to be their API url, see readme for details
  hive: http://hiveleakdbtnp76ulyhi52eag6c6tyc3xw7ez7iqy6wc34gd2nekazyd.onion.ly/
  rook: http://gamol6n6p2p4c3ad7gxmx3ur7wwdwlywebo2azv3vv5qlmjmole2zbyd.onion.ly/
  xeon: http://zeonrefpbompx6rwdqa5hxgtp2cxgfmoymlli3azoanisze33pp3x3yd.onion.ws/chat
  vice society: http://vsociethok6sbprvevl4dlwbqrzyhxcxaqpvcqt5belwvsuxaxsutyad.onion.ly/
  synACK: http://xqkz2rmrqkeqf6sjbrb47jfwnqxcd4o2zvaxxzrpbh2piknms37rw2ad.onion.ws/
  spook: http://spookuhvfyxzph54ikjfwf2mwmxt572krpom7reyayrmxbkizbvkpaid.onion.ws/blog/
  snatch: http://hl66646wtlp2naoqnhattngigjp5palgqmbwixepcjyq5i534acgqyad.onion.ly/index.php
  saudi: http://662m7dfcpfsmeetqucdekz3rn4a6dxsxbdjwd6iz3rwnogjsj7i3hxad.onion.ly/
  sabbath: http://54bb47h.blog/
  rransom: http://t2tqvp4pctcr7vxhgz5yd5x4ino5tw7jzs3whbntxirhp32djhi7q3id.onion.ly/check_payment_form
  robinhood: https://robinhoodleaks.tumblr.com/
  ransomsupport: http://d57uremugxjrafyg.onion.ws/
  quantum: http://quantum445bh3gzuyilxdzs5xdepf3b7lkcupswvkryf3n7hgzpxebid.onion.ly/
  qlocker: http://gvka2m4qt5fod2fltkjmdk4gxh5oxemhpgmnmtjptms6fkgfzdd62tad.onion.ly/
  prometheus: http://promethw27cbrcot.onion.ws/blog/
  payload: http://vbmisqjshn4yblehk2vbnil53tlqklxsdaztgphcilto3vdj4geao5qd.onion.ly/
  pandora: http://vbfqeh5nugm6r2u2qvghsdxm3fotf5wbxb5ltv6vw77vus5frdpuaiid.onion.ly/
  noname: http://vfokxcdzjbpehgit223vzdzwte47l3zcqtafj34qrr26htjo4uf3obid.onion.ly/
  nightsky: http://gg5ryfgogainisskdvh4y373ap3b2mxafcibeh2lvq5x7fx76ygcosad.onion.ly/
  networm: http://n3twormruynhn3oetmxvasum2miix2jgg56xskdoyihra4wthvlgyeyd.onion.ly/
  mydecryptor: http://58b87e60649ccc808ac8mstiejnj.5s4ixqul2enwxrqv.onion.ly/
  mountlocker: http://mountnewsokhwilx.onion.ly/
  moses: https://moses-staff.se/
  medusa: http://qd7pcafncosqfqu3ha6fcx4h6sr7tzwagzpcdcnytiw3b6varaeqv5yd.onion.ly/
  mbc: http://xembshruusobgbvxg4tcjs3jpdnks6xrr6nbokfxadcnlc53yxir22ad.onion.ly/
  lolkek: http://mmeeiix2ejdwkmseycljetmpiwebdvgjts75c63camjofn2cjdoulzqd.onion.ws/
  lockfile: http://zqaflhty5hyziovsxgqvj2mrz5e5rs6oqxzb54zolccfnvtn5w2johad.onion.ly/
  karma: http://3nvzqyo6l4wkrzumzu5aod7zbosq4ipgf7ifgj3hsvbcr5vcasordvqd.onion.ws/
  karakurt: https://karakurt.tech/
  hotarus: http://r6d636w47ncnaukrpvlhmtdbvbeltc6enfcuuow3jclpmyga7cz374qd.onion.ly/
  holyghost: http://matmq3z3hiovia3voe2tix2x54sghc3tszj74xgdy4tqtypoycszqzqd.onion.ws/
  hitler: http://hitleransomware.cf/
  haron2: http://midasbkic5eyfox4dhnijkzc7v7e4hpmsb2qgux7diqbpna4up4rtdad.onion.ly/
  haron1: http://ft4zr2jzlqoyob7yg4fcpwyt37hox3ajajqnfkdvbfrkjioyunmqnpad.onion.ws/
  groove(fake): http://ws3dh6av66sjbxxkjpw5ao3wqzmtejnkzheswm4dz5rrwvular7xvkqd.onion.ly/
  grief: http://griefcameifmv4hfr3auozmovz5yi6m3h3dwbuqw7baomfxoxz4qteid.onion.ws/
  entropy: http://leaksv7sroztl377bbohzl42i3ddlfsxopcb6355zc7olzigedm5agad.onion.ws/
  echoraix: http://veqlxhq7ub5qze3qy56zx2cig2e6tzsgxdspkubwbayqije6oatma6id.onion.ly/
  dopple: http://hpoo4dosa3x4ognfxpqcrjwnsigvslm7kv6hvmhh2yqczaxy3j6qnwad.onion.ly/
  darkrypt: https://darkrypt.io/
  corporate: http://hxt254aygrsziejn.onion.ws/
  cooming: http://coomingproject.com/
  bonaci: http://bonacifryrxr4siz6ptvokuihdzmjzpveruklxumflz5thmkgauty2qd.onion.ly/
  blackcat: http://alphvmmm27o3abo3r2mlmjrpdmzle3rykajqc5xsj7j7ejksbpsa36ad.onion.ly/
  blackbyte: https://dlyo7r3n4qy5fzv4645nddjwarj7wjdd6wzckomcyc7akskkxp4glcad.onion.ly/
  atomsilo: http://l5cjga2ksw6rxumu5l4xxn3cmahhi2irkbwg3amx6ajroyfmfgpfllid.onion.ly/
  admin: http://adminavf4cikzbv6mbbp7ujpwhygnn2t3egiz2pswldj32krrml42wyd.onion.ly/  
  
  

# slack webhooks
notifications:
  dest1:
    # type of notification
    # valid options: slack, discord, Teams
    type: slack

    # url for the webhook (slack, discord, Teams)
    url: https://hooks.slack.com/services/something/goes/here

    # should new victim notifications be sent to this webhook?
    new_victims: true

    # should removed victim notifications be sent to this webhook?
    removed_victims: true

    # should notifications be sent to this webhook if a site is detected as down?
    down_sites: true

    # should errors be sent to this webook?
    errors: true

    # may in the future add support for not sending leak site links
    # if you actively want this, open an issue (or make a PR)
  dest2:
    type: slack
    url: https://hooks.slack.com/services/something/else/goes/here
    new_victims: true
    removed_victims: true
    down_sites: true
    errors: false

# how many seconds to wait for a connection
# this is used to check if the site is up, and doesn't wait
# for the full page data to be downloaded
timeout: 30

# tor proxy settings
# the values set below are for the provided docker-compose.yml
# adjust for your own custom environment
proxy:
  # hostname for the proxy
  hostname: proxy

  # port for the SOCKS proxy
  socks_port: 9050

  # port for the tor control service
  control_port: 9051

  # password for the tor control service
  password: password
